# Generated by Django 5.2.6 on 2026-08-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0020_external_sync_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='deletion_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('deleting', 'Deleting'), ('failed', 'Failed'), ('completed', 'Completed')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='media',
            name='metadata_sources',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='media',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='media',
            name='revision',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='media',
            name='storage_backend',
            field=models.CharField(choices=[('legacy_local', 'Legacy local'), ('aws', 'AWS')], db_index=True, default='legacy_local', max_length=20),
        ),
    ]
