# Generated by Django 5.2.6 on 2026-08-02 00:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0021_aws_domain_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAssetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('active', 'Active'), ('retired', 'Retired')], db_index=True, default='candidate', max_length=20)),
                ('manifest_key', models.CharField(max_length=1024)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_versions', to='files.media')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('original', 'Original'), ('hls_master', 'HLS master'), ('hls_variant', 'HLS variant'), ('hls_segment', 'HLS segment'), ('poster', 'Poster'), ('thumbnail', 'Thumbnail'), ('subtitle', 'Subtitle'), ('audio', 'Audio')], db_index=True, max_length=30)),
                ('s3_key', models.CharField(max_length=1024)),
                ('checksum', models.CharField(blank=True, max_length=160)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='files.mediaassetversion')),
            ],
            options={
                'ordering': ('kind', 's3_key', 'id'),
            },
        ),
        migrations.AddField(
            model_name='media',
            name='active_asset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_media', to='files.mediaassetversion'),
        ),
        migrations.AddIndex(
            model_name='mediaassetversion',
            index=models.Index(fields=['media', 'status'], name='files_av_media_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['version', 'kind'], name='files_asset_version_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.UniqueConstraint(fields=('version', 's3_key'), name='files_asset_key_per_version_uniq'),
        ),
    ]
