# Generated by Django 5.2.6 on 2026-08-02 00:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0022_media_asset_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaIngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_title_snapshot', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('upload', 'Upload'), ('hls_zip', 'HLS ZIP'), ('youtube', 'YouTube')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('completed', 'Completed')], db_index=True, default='queued', max_length=20)),
                ('stage', models.CharField(blank=True, max_length=64)),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cancel_requested', models.BooleanField(default=False)),
                ('cleanup_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('failed', 'Failed'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('safe_error', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to='files.media')),
            ],
            options={
                'ordering': ('queued_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MediaJobAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('completed', 'Completed')], db_index=True, default='queued', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('mediaconvert_job_id', models.CharField(blank=True, max_length=255)),
                ('provider_status', models.CharField(blank=True, max_length=64)),
                ('provider_phase', models.CharField(blank=True, max_length=64)),
                ('provider_percent_complete', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('checkpoint_evidence', models.JSONField(blank=True, default=dict)),
                ('diagnostic_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='files.mediaingestionjob')),
            ],
            options={
                'ordering': ('job', 'sequence'),
            },
        ),
        migrations.AddField(
            model_name='mediaassetversion',
            name='attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_version', to='files.mediajobattempt'),
        ),
        migrations.CreateModel(
            name='MediaJobCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('available', 'Available'), ('unavailable', 'Unavailable'), ('failed_retryable', 'Failed retryable')], db_index=True, default='pending', max_length=20)),
                ('input_fingerprint', models.CharField(blank=True, max_length=255)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='files.mediajobattempt')),
            ],
            options={
                'ordering': ('attempt', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProcessingLease',
            fields=[
                ('singleton_key', models.CharField(default='default', editable=False, max_length=20, primary_key=True, serialize=False)),
                ('owner_token', models.CharField(blank=True, max_length=255)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processing_leases', to='files.mediajobattempt')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processing_leases', to='files.mediaingestionjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='mediaingestionjob',
            index=models.Index(fields=['status', 'queued_at', 'id'], name='files_job_fifo_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediaingestionjob',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='files_job_progress_range'),
        ),
        migrations.AddConstraint(
            model_name='mediajobattempt',
            constraint=models.UniqueConstraint(fields=('job', 'sequence'), name='files_attempt_job_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='mediajobcheckpoint',
            constraint=models.UniqueConstraint(fields=('attempt', 'name'), name='files_checkpoint_attempt_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='processinglease',
            constraint=models.CheckConstraint(condition=models.Q(('singleton_key', 'default')), name='files_processing_lease_default_key'),
        ),
    ]
