# Generated by Django 5.2.6 on 2026-08-02 03:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0023_ingestion_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_kind', models.CharField(choices=[('file', 'File'), ('hls', 'HLS package')], max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('uploading', 'Uploading'), ('paused', 'Paused'), ('verifying', 'Verifying'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='waiting', max_length=20)),
                ('expected_total_size', models.PositiveBigIntegerField()),
                ('expected_file_count', models.PositiveIntegerField(default=1)),
                ('confirmed_bytes', models.PositiveBigIntegerField(default=0)),
                ('confirmed_file_count', models.PositiveIntegerField(default=0)),
                ('file_fingerprint', models.CharField(blank=True, max_length=255)),
                ('part_size', models.PositiveIntegerField(default=16777216)),
                ('create_idempotency_key', models.CharField(max_length=255, unique=True)),
                ('completion_idempotency_key', models.CharField(blank=True, max_length=255)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('safe_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='browser_upload_session', to='files.mediaingestionjob')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='browser_upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BrowserUploadObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relative_path', models.CharField(max_length=1024)),
                ('s3_key', models.CharField(max_length=1500, unique=True)),
                ('strategy', models.CharField(choices=[('multipart', 'Multipart'), ('single_put', 'Single PUT')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('verified', 'Verified'), ('aborted', 'Aborted')], db_index=True, default='pending', max_length=20)),
                ('expected_size', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=255)),
                ('multipart_upload_id', models.CharField(blank=True, max_length=1024)),
                ('checksum', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_objects', to='files.browseruploadsession')),
            ],
            options={
                'ordering': ('session', 'relative_path', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BrowserUploadLease',
            fields=[
                ('singleton_key', models.CharField(default='default', editable=False, max_length=20, primary_key=True, serialize=False)),
                ('owner_token', models.CharField(blank=True, max_length=255)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload_leases', to='files.mediaingestionjob')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload_leases', to='files.browseruploadsession')),
            ],
        ),
        migrations.CreateModel(
            name='BrowserUploadPart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('part_number', models.PositiveIntegerField()),
                ('etag', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='files.browseruploadobject')),
            ],
            options={
                'ordering': ('upload_object', 'part_number'),
                'constraints': [models.UniqueConstraint(fields=('upload_object', 'part_number'), name='files_upload_part_object_number_uniq'), models.CheckConstraint(condition=models.Q(('part_number__gte', 1), ('part_number__lte', 10000)), name='files_upload_part_number_range'), models.CheckConstraint(condition=models.Q(('size__gt', 0)), name='files_upload_part_size_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='browseruploadsession',
            constraint=models.CheckConstraint(condition=models.Q(('expected_total_size__gt', 0)), name='files_upload_expected_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='browseruploadsession',
            constraint=models.CheckConstraint(condition=models.Q(('expected_file_count__gt', 0)), name='files_upload_expected_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='browseruploadsession',
            constraint=models.CheckConstraint(condition=models.Q(('confirmed_bytes__lte', models.F('expected_total_size'))), name='files_upload_confirmed_size_lte_expected'),
        ),
        migrations.AddConstraint(
            model_name='browseruploadsession',
            constraint=models.CheckConstraint(condition=models.Q(('confirmed_file_count__lte', models.F('expected_file_count'))), name='files_upload_confirmed_count_lte_expected'),
        ),
        migrations.AddConstraint(
            model_name='browseruploadsession',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='files_upload_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='browseruploadobject',
            constraint=models.UniqueConstraint(fields=('session', 'relative_path'), name='files_upload_object_session_path_uniq'),
        ),
        migrations.AddConstraint(
            model_name='browseruploadobject',
            constraint=models.CheckConstraint(condition=models.Q(('expected_size__gt', 0)), name='files_upload_object_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='browseruploadlease',
            constraint=models.CheckConstraint(condition=models.Q(('singleton_key', 'default')), name='files_upload_lease_default_key'),
        ),
    ]
