# Generated by Django 5.2.6 on 2026-08-02 05:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0024_browser_upload_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('upload_source', 'Upload source'), ('original', 'Original'), ('candidate', 'Candidate')], max_length=32)),
                ('s3_key', models.CharField(max_length=1500)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=255)),
                ('checksum', models.CharField(max_length=255)),
                ('cleanup_status', models.CharField(choices=[('pending', 'Pending'), ('retained', 'Retained'), ('deleted', 'Deleted'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('safe_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('attempt', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MediaJobWarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('attempt', 'created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='browseruploadobject',
            name='promoted_s3_key',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='browseruploadobject',
            name='promotion_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('copying', 'Copying'), ('verified', 'Verified'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='mediajobattempt',
            name='client_request_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mediajobattempt',
            name='next_poll_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediajobattempt',
            name='provider_last_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediajobattempt',
            name='provider_unchanged_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediajobattempt',
            name='submission_intent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediajobattempt',
            name='template_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediajobattempt',
            name='template_version',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='mediajobattempt',
            index=models.Index(fields=['status', 'next_poll_at'], name='files_attempt_due_idx'),
        ),
        migrations.AddField(
            model_name='attemptartifact',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='files.mediajobattempt'),
        ),
        migrations.AddField(
            model_name='mediajobwarning',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='files.mediajobattempt'),
        ),
        migrations.AddConstraint(
            model_name='attemptartifact',
            constraint=models.UniqueConstraint(fields=('attempt', 's3_key'), name='files_artifact_attempt_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attemptartifact',
            constraint=models.CheckConstraint(condition=models.Q(('s3_key__startswith', 'uploads/'), ('s3_key__startswith', 'originals/'), ('s3_key__startswith', 'candidates/'), _connector='OR'), name='files_artifact_managed_root'),
        ),
        migrations.AddConstraint(
            model_name='mediajobwarning',
            constraint=models.UniqueConstraint(fields=('attempt', 'code'), name='files_warning_attempt_code_uniq'),
        ),
    ]
