# Generated by Django 5.2.6 on 2026-08-02 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0025_mediaconvert_orchestration'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeCookieVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_payload', models.BinaryField()),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('invalid', 'Invalid')], db_index=True, default='active', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-uploaded_at', 'id'),
            },
        ),
    ]
