# Generated by Django 5.2.6 on 2026-08-03 02:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0026_youtube_cookie_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPlaybackProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_seconds', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_progress', to='files.mediaassetversion')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_progress', to='files.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_playback_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'updated_at'], name='files_pb_user_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('media', 'user'), name='files_playback_media_user_uniq')],
            },
        ),
    ]
